name: Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'sync'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        run: echo "Workflow triggered for environment: ${{ github.event.inputs.environment }}"
#dvd