name: Apply Terraform to Environment

on:
  workflow_run:
    workflows: ["Sync S3 with GitHub"]
    types:
      - completed

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform-version: <TERRAFORM_VERSION>

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var environment=${{ env.TARGET }}

      - name: Terraform Apply
        run: terraform apply -var environment=${{ env.TARGET }} --auto-approve
