name: Terraform To Integ
on:
  workflow_run:
    workflows: ["Sync S3 with GitHub"]
    types:
      - completed

jobs:
  TerraformToInteg:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Terraform Common
        run: |
          echo "Running Terraform Common"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "ENVIRONMENT=common"

      - name: Terraform Environment
        run: |
          echo "Running Terraform Environment"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "ENVIRONMENT=integ"
