name: Sync S3 with GitHub

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add workflow_dispatch event for manual triggering
   inputs:
    environment:
      description: 'Environment for Terraform'
      required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Sync .py files with S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          bucket_name="test21223"
          aws s3 sync . "s3://test21223" --include "*.py" --delete

  TerraformToTeam:
    needs: sync
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'team'}}
    steps:
      - name: Terraform Common
        run: |
          echo "Running Terraform Common"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "ENVIRONMENT=common"

      - name: Terraform Environment
        run: |
          echo "Running Terraform Environment"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "ENVIRONMENT=team"

  TerraformToInteg:
    needs: sync
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'integ'}}
    steps:
      - name: Terraform Common
        run: |
          echo "Running Terraform Common"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "ENVIRONMENT=common"

      - name: Terraform Environment
        run: |
          echo "Running Terraform Environment"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "ENVIRONMENT=integ"

  TerraformToProd:
    needs: sync
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'prod' }}
    steps:
      - name: Terraform Common
        run: |
          echo "Running Terraform Common"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "ENVIRONMENT=common"

      - name: Terraform Environment
        run: |
          echo "Running Terraform Environment"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "ENVIRONMENT=prod"

  ManualTrigger:
    needs: sync
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Run workflow
        run: gh workflow run workflow.yaml -f environment=terraformtointeg
