name: Sync S3 with GitHub

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add workflow_dispatch event for manual triggering
    inputs:
      environment:
        description: 'Environment for Terraform'
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest

    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.inputs.environment, 'prod') || startsWith(github.event.inputs.environment, 'team') || startsWith(github.event.inputs.environment, 'integ')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Sync .py files with S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          bucket_name="test21223"
          aws s3 sync . "s3://test21223" --include "*.py" --delete
