name: Sync S3 with GitHub

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Generate Unique Bucket Name
        id: generate_bucket_name
        run: |
          echo "BucketName=bucket-$(date +%Y%m%d%H%M%S)"

      - name: Create S3 Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          bucket_name="${{ steps.generate_bucket_name.outputs.BucketName }}"
          aws s3api create-bucket --bucket "$bucket_name" --region ap-south-1 --create-bucket-configuration LocationConstraint=ap-south-1

      - name: Sync .py files with S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          bucket_name="${{ steps.generate_bucket_name.outputs.BucketName }}"
          aws s3 sync . "s3://$bucket_name" --include "*.py" --delete

#gygygh
#