name: Sync S3 with GitHub

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'sync' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Sync .py files with S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          bucket_name="test21223"
          aws s3 sync . "s3://test21223" --include "*.py" --delete


  TerraformToTeam:
    runs-on: self-hosted
    environment: Team
    if: ${{ github.event.inputs.environment == 'team' }}

    steps:
      - name: Terraform Common
        run: |
          echo "Running Terraform Common"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "ENVIRONMENT=common"

      - name: Terraform Environment
        run: |
          echo "Running Terraform Environment"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "ENVIRONMENT=${{ env.TARGET }}"


  TerraformToInteg:
    runs-on: self-hosted
    environment: Integ
    if: ${{ github.event.inputs.environment == 'integ' }}

    steps:
      - name: Terraform Common
        run: |
          echo "Running Terraform Common"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "ENVIRONMENT=common"

      - name: Terraform Environment
        run: |
          echo "Running Terraform Environment"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "ENVIRONMENT=${{ env.TARGET }}"


  TerraformToProd:
    runs-on: self-hosted
    environment: Production
    if: ${{ github.event.inputs.environment == 'prod' }}

    steps:
      - name: Terraform Common
        run: |
          echo "Running Terraform Common"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "ENVIRONMENT=common"

          
 inputs:
  environment:
    description: 'The environment to deploy'
    default: 'sync'
